# Generated by Django 2.1.1 on 2018-10-09 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '商品分类和商品关系',
                'verbose_name_plural': '商品分类和商品关系',
                'db_table': 'category_goods',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='商品分类名称')),
                ('number', models.IntegerField(default=0, verbose_name='排序字段')),
                ('image', models.CharField(default='/static/images/banner01.jpg', max_length=100, verbose_name='分类展示图片')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, null=True, verbose_name='评论的内容')),
                ('vote_number', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 10, 9, 20, 39, 2, 128438), verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('abstract', models.CharField(max_length=200, null=True, verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='商品价格')),
                ('unit', models.CharField(max_length=20, verbose_name='商品售卖单位')),
                ('stock', models.IntegerField(default=0, verbose_name='商品库存')),
                ('desc', models.TextField(null=True, verbose_name='详细介绍')),
                ('pic', models.CharField(default='/static/images/goods/goods003.jpg', max_length=200, verbose_name='商品默认图片')),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='goods.CategoryModel', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsModel', verbose_name='商品')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsModel', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel', verbose_name='评论的用户'),
        ),
        migrations.AddField(
            model_name='categorygoodsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.CategoryModel', verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='categorygoodsmodel',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsModel', verbose_name='商品'),
        ),
    ]
