# Generated by Django 2.1.1 on 2018-10-10 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='人气指数'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 9, 29, 46, 441576), verbose_name='创建时间'),
        ),
    ]
